### ISSUE TITLE
Quick start guide from docs currently not working

### ISSUE THREAD

**Issue by gunnarlan** [metno/genchem#13]
Following the [guide](https://genchem.readthedocs.io/en/latest/GenChemDoc_quickstart.html), at step 2, running:

`./do.testChems EmChem19a`

I get the error:
```
At line 160 of file Config_module.f90
Fortran runtime error: Cannot match namelist object name 'voc'
```

Presumably because of an inconsistency in the `Config_module.f90` and the relevant `config_box.nml` in the box model.

Commenting out the VOC in the box config namelist fixes the issue, but would be good if the quick start guide worked

**Comment by mifads** [comment]
Odd. I just made a new working directory of a clean genchem system, ran the same command as you, and all worked well. Exactly which VOC line did you have to comment out?

**Comment by gunnarlan** [comment]
Line 39 in `config_box.nml`:

```
38 emis_kgm2day = 'nox', 18.3, ! NOx, kg/m2/day, as in MCM/CRI tests
39             'voc', 15.4  ! NMVOC !Commented out this line
```

In the `tmp_work` folder created in step 1 of the guide.

**Comment by mifads** [comment]
Hmm. I can't see why this should fail, but namelist reading is ill-defined in fortran. My compiler is:
```
gfortran --version
GNU Fortran (Ubuntu 13.2.0-4ubuntu3) 13.2.0
```
though this has worked for years on my (and other's) PCs. Do you use something other than gfortran?

**Comment by gunnarlan** [comment]
I'm running:
```
gfortran --version
GNU Fortran (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
```

**Comment by mifads** [comment]
@WillemVanCaspel - do you see the same issue?

**Comment by gunnarlan** [comment]
Yes, removing the comment `! NOx, kg/m2/day, as in MCM/CRI tests` in line 38 fixed the issue!

So it's probably a comiler thing

**Comment by mifads** [comment]
I just committed a changed config file. Seems like comments are allowed besides scalars, but not in array specs. Can you test please with your compiler. If all works well, we can close this issue.

**Comment by gunnarlan** [comment]
Sorry, the issue persists 

Removing the exclamation mark ! from line 39 does solve the issue, but that may break some conventions with regards to comments?

**Comment by mifads** [comment]
Ah, my bad. Try again please.

**Comment by gunnarlan** [comment]
Yes, works now - thanks  a lot!

**Comment by gunnarlan** [comment]
Yes, works now - thanks a lot!
